### ISSUE TITLE
Merging with other?

### ISSUE THREAD

**Issue by astronyu** [milewski/MiningRentalAutoPilot#2]
Hi, I know this is now discontinued but perhaps merge it with [https://github.com/RainbowMiner/RainbowMiner](url) ?

**Comment by milewski** [comment]
Why thou that looks like a much better solution

**Comment by astronyu** [comment]
Currently it doesn't have the option ;)

**Comment by milewski** [comment]
That looks like has been written in .net I had my version written in nodejs ..
